#!/bin/bash
# run_aiesim.sh — build the hand-written ps.so and run aiesimulator for one
# compiler arm of the Peano-vs-Chess A/B (see ../README-COMPILER-AB.md).
#
# The aiesim workdir is generated by aiecc --aiesim (see ../bench_compiler_ab.sh
# step "aiesim"; the arm dirs hold design.mlir, mm_32x64x128.o and the generated
# design.mlir.prj/). This script:
#   1. builds sim/ps/ps.so = genwrapper_for_ps.cpp + txn_replay_main.cpp
#      + test_library.cpp + libmemory_allocator_sim_aie.a
#   2. copies the arm's insts.txt next to the sim as insts.txt
#   3. runs aiesimulator --pkg-dir=<prj>/sim, prints the PASS/FAIL + C stats
#
# Issue guards:
#   #1911  aiecc --aiesim silently skips ps.so generation when clang++ is not
#          on PATH (exit 0, unusable workdir). This script builds ps.so by hand
#          with system g++ — and FAILS LOUDLY below if the build did not
#          actually produce a ps.so.
#   #1909  aiecc --aie-mlir-to-shim-solution emits an EMPTY aieshim_solution
#          .aiesol ("Placement": []) for every npu2 design, which would make
#          aiesimulator silently useless. We warn loudly when that is detected
#          (the TXN-replay ps.so below is the workaround that makes such
#          designs sim-able).
#   #1908  Vitis 2026.1's aie2psimmsm segfaults on ANY npu2 design; 2025.2
#          works. Default VITIS to 2025.2 and refuse 2026.1 unless forced.
#
# Needs: strixhalo (Vitis aietools + mlir-aie + license), g++.
# NOTE: aiesimulator is slow on the full 128x2048x8192 design (millions of
# cycles); start with WAIT_US small / a shrunk design to validate plumbing.
set -euo pipefail

AISIM_DIR="$(cd "$(dirname "$0")" && pwd)"
TESTS="$(dirname "$AISIM_DIR")"
MLIR_AIE="${MLIR_AIE:-$HOME/mlir-aie}"
# Issue #1908: 2025.2 is the WORKING aiesimulator for aie2p — 2026.1's
# aie2psimmsm segfaults at startup on any npu2 design (empty aiesol + missing
# aie2p_8x4_device.json). Override with VITIS=~/Xilinx/2026.1 at your own risk.
VITIS="${VITIS:-$HOME/Xilinx/2025.2}"
case "$VITIS" in
  *2026.1*)
    echo "WARNING (#1908): Vitis 2026.1 aie2psimmsm segfaults on npu2 designs;" >&2
    echo "  2025.2 is the verified-working aiesimulator. Forcing 2026.1 anyway." >&2
    ;;
esac
AIETOOLS="$VITIS/Vitis/aietools"
TL_INC="$MLIR_AIE/.venv/lib/python3.14/site-packages/mlir_aie/runtime_lib/x86_64/test_lib/include"
TL_LIB="$MLIR_AIE/.venv/lib/python3.14/site-packages/mlir_aie/runtime_lib/x86_64/test_lib/lib"
XAIE_INC="$MLIR_AIE/install/runtime_lib/x86_64/xaiengine/include"
XAIE_LIB="$MLIR_AIE/install/runtime_lib/x86_64/xaiengine/lib"
GENWRAP="$MLIR_AIE/install/aie_runtime_lib/AIE2P/aiesim/genwrapper_for_ps.cpp"

# workdir with the generated aiesim (*.mlir.prj/) — from bench_compiler_ab
PRJ_DIR="${1:?usage: run_aiesim.sh <arm-workdir> [WAIT_US] [insts-name]}"
WAIT_US="${2:-1000}"
INSTS="${3:-insts.txt}"
# locate the prj dir (design.mlir.prj for aiecc designs, <name>.mlir.prj for raw)
PRJ="$PRJ_DIR/design.mlir.prj"
[ -d "$PRJ" ] || PRJ=$(ls -d "$PRJ_DIR"/*.mlir.prj 2>/dev/null | head -1)
[ -n "$PRJ" ] && [ -d "$PRJ" ] || { echo "ERROR: no *.mlir.prj under $PRJ_DIR" >&2; exit 1; }

for p in "$GENWRAP" "$PRJ/aie_inc.cpp" "$AIETOOLS/bin/aiesimulator"; do
  [ -e "$p" ] || { echo "ERROR: missing $p" >&2; exit 1; }
done
[ -e "$PRJ_DIR/$INSTS" ] || { echo "ERROR: $PRJ_DIR/$INSTS not found" >&2; exit 1; }

# Issue #1909: detect the empty aieshim_solution.aiesol ({"Placement": []})
# that aiecc emits for every npu2 design. Without the TXN-replay ps.so this
# workdir is unusable — warn loudly so nobody mistakes it for a real sim.
if [ -f "$PRJ/aieshim_solution.aiesol" ]; then
    if grep -q '"Placement"[[:space:]]*:[[:space:]]*\[\]' "$PRJ/aieshim_solution.aiesol"; then
        echo "WARNING (#1909): $PRJ/aieshim_solution.aiesol has EMPTY Placement —" >&2
        echo "  aiecc --aie-mlir-to-shim-solution cannot place this npu2 design." >&2
        echo "  The TXN-replay ps.so below drives it anyway; do NOT use the" >&2
        echo "  aiesol alone (it would make aiesimulator silently useless)." >&2
    fi
fi

export PATH="$AIETOOLS/bin:/opt/xilinx/xrt/bin:$PATH"
export XILINXD_LICENSE_FILE="$HOME/.Xilinx/Xilinx.lic"
export LD_LIBRARY_PATH="$XAIE_LIB:$AIETOOLS/lib/lnx64.o:$AIETOOLS/lib/lnx64.o/Ubuntu:$AIETOOLS/data/osci_systemc/lib/lnx64:${LD_LIBRARY_PATH:-}"

echo "== 1/3 build ps.so =="
mkdir -p "$PRJ/sim/ps"
g++ -O2 -shared -fPIC -fpermissive \
  -Wno-deprecated-declarations -Wno-format-security \
  -DSC_INCLUDE_DYNAMIC_PROCESSES -D__AIESIM__ -D__PS_INIT_AIE__ \
  -DAIE_OPTION_SCALAR_FLOAT_ON_VECTOR -D__AIEARCH__=21 \
  "-Dmain(...)=ps_main(...)" \
  "-DWAIT_US=$WAIT_US" \
  ${AISIM_DEFS:-} \
  -I "$PRJ" \
  -I "$AIETOOLS/include" \
  -I "$XAIE_INC" \
  -I "$AIETOOLS/data/osci_systemc/include" \
  -I "$AIETOOLS/include/xtlm/include" \
  -I "$AIETOOLS/include/common_cpp/common_cpp_v1_0/include" \
  -I "$TL_INC" \
  "$GENWRAP" "$TESTS/aiesim/txn_replay_main.cpp" \
  "$MLIR_AIE/runtime_lib/test_lib/test_library.cpp" \
  "$TL_LIB/libmemory_allocator_sim_aie.a" \
  -L "$XAIE_LIB" -lxaienginecdo \
  -L "$AIETOOLS/lib/lnx64.o" -L "$AIETOOLS/lib/lnx64.o/Ubuntu" \
  -L "$AIETOOLS/data/osci_systemc/lib/lnx64" \
  -Wl,--as-needed -lsystemc -lxtlm \
  -o "$PRJ/sim/ps/ps.so" 2>&1 | tail -15
# Issue #1911: the aiecc --aiesim flow silently exits 0 with NO ps.so when
# clang++ is missing. Here g++ builds it by hand — but verify the artifact
# actually exists and is non-empty (a failed compile above must not slip
# through as a "successful" sim workdir).
if [ ! -s "$PRJ/sim/ps/ps.so" ]; then
    echo "ERROR (#1911): ps.so was not produced — the g++ ps.so build failed above." >&2
    echo "  Check the compiler diagnostics (aiecc --aiesim silently skips ps.so" >&2
    echo "  generation when clang++ is missing from PATH; this harness must not)." >&2
    exit 1
fi
echo "  OK: $PRJ/sim/ps/ps.so ($(stat -c%s "$PRJ/sim/ps/ps.so") B)"

echo "== 2/3 stage insts =="
cp "$PRJ_DIR/$INSTS" "$PRJ/insts.txt"
echo "  OK: $PRJ/insts.txt"

echo "== 3/3 run aiesimulator =="
cd "$PRJ"
aiesimulator --pkg-dir=sim --simulation-cycle-timeout=200000000 2>&1 | \
  grep -v -E "^\[INFO\]|^\[WARNING\]" | tail -40
echo "aiesimulator exit=$?"
