#!/usr/bin/env python3
"""census_autopr.py — auto-file a draft PR when the new-model watcher finds an
uncovered architecture that *looks like* a known family.

The watcher (hf_new_models.py) detects new HF archs the engine registry
doesn't map. Mapping is normally a manual bitnet_model.h edit. For the common
case where HF's model_type is just a variant of a family the engine already
knows (e.g. `kimik3` vs `kimi_k3`, `qwen35moe` vs `qwen35`), this module
guesses the candidate mapping and opens a DRAFT pull request proposing the
one-line alias — turning "discover + edit" into "review + merge".

Only fires for *plausible* candidates (edit distance to an existing mapping,
or a known-family substring). Genuinely-new architectures (no existing family
relation) are left as a manual alert — they need a real engine implementation,
not an alias.

Usage (from hf_new_models.py after finding uncovered):
    from census_autopr import maybe_file_draft_pr
    maybe_file_draft_pr(uncovered, dry_run=...)

Environment:
  GITHUB_TOKEN / gh CLI — uses `gh` if available, else no-ops with a log line.
  CENSUS_DRY_RUN=1 — print what would be filed, don't touch GitHub.
  CENSUS_SKIP_PR=1 — never open PRs (alert only).
"""
import json, os, re, subprocess, sys, difflib
from urllib.parse import urlparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENGINE = os.path.join(ROOT, "include", "rocm_cpp", "bitnet_model.h")
SELFCHECK = os.path.join(ROOT, "Testing", "census_tail_sweep.py")

# Token names the engine defines (for the proposed line's RHS). Pulled from the
# header once, cached.
_TOKEN_RE = re.compile(r"RCPP_ARCH_[A-Z0-9_]+")

_KNOWN = None  # {arch_string: token_name}


def _known_mappings():
    """Parse include/rocm_cpp/bitnet_model.h for string -> RCPP_ARCH_* pairs."""
    global _KNOWN
    if _KNOWN is not None:
        return _KNOWN
    known = {}
    try:
        with open(ENGINE) as f:
            for line in f:
                m = re.search(r'strcmp\(s,\s*"([a-z0-9_]+)"\)\s*==\s*0\)\s*return\s+(RCPP_ARCH_[A-Z0-9_]+)', line)
                if m:
                    known[m.group(1)] = m.group(2)
    except OSError as e:
        print(f"[autopr] cannot read {ENGINE}: {e}", file=sys.stderr)
    _KNOWN = known
    return known


def _norm(s):
    """Normalize an arch string for comparison: drop non-alnum, lowercase."""
    return re.sub(r"[^a-z0-9]", "", s.lower())


def _guess(uncovered_arch):
    """Return (candidate_arch_string, token_name) or None for an uncovered arch."""
    known = _known_mappings()
    n = _norm(uncovered_arch)
    if not n:
        return None

    # 1. Exact match on a normalized known string (e.g. kimik3 vs kimi_k3).
    for s, tok in known.items():
        if _norm(s) == n:
            return s, tok

    # 2. Edit-distance to a known family (<=2 substitutions/dels, normalized).
    best, best_d = None, 3
    for s, tok in known.items():
        d = difflib.SequenceMatcher(None, n, _norm(s)).ratio()
        if d > 0.8 and s != uncovered_arch:  # 80%+ similar
            score = 1 - d
            if score < best_d:
                best, best_d = (s, tok), score
    if best:
        return best

    # 3. Known-family substring prefix (e.g. "qwen35moe" starts with "qwen35").
    fams = sorted(known.keys(), key=len, reverse=True)
    for s in fams:
        if n.startswith(_norm(s)) and len(n) > len(_norm(s)):
            return s, known[s]

    return None


def _proposed_lines(arch, target):
    """Proposed bitnet_model.h line(s) for arch -> target token."""
    return [f'    if (strcmp(s, "{arch}") == 0) return {target};  // census-auto']


def _selfcheck_has(arch):
    try:
        with open(SELFCHECK) as f:
            return arch in f.read()
    except OSError:
        return False


def _open_draft_pr(arch, target, models):
    """Open a draft PR proposing the alias. Returns PR url or None."""
    branch = f"census/auto-map-{arch}"
    body = (
        f"## Auto-filed by the census watcher\n\n"
        f"The daily new-model watcher found an uncovered HF architecture "
        f"(`{arch}`) that looks like a known family. This draft proposes "
        f"the one-line alias so it stops surfacing as a coverage gap.\n\n"
        f"**Proposed mapping:** `{arch}` → `{target}` "
        f"(candidate, needs human review)\n\n"
        f"**Models triggering it:** {', '.join(models[:5])}\n\n"
        f"**Steps for the reviewer:**\n"
        f"1. Confirm `{arch}` really is the `{target}` family (check the "
        f"model config / paper).\n"
        f"2. If yes, mark ready + merge. If it's a *new* architecture, close "
        f"this and add a real engine implementation.\n\n"
        f"Auto-generated by `Testing/census_autopr.py` — the mapping is a "
        f"*guess*, not verified."
    )
    cmds = [
        ["git", "switch", "-c", branch],
        ["git", "add", os.path.relpath(ENGINE, ROOT)],
        ["git", "commit", "-m", f"fix(census): auto-propose {arch} -> {target}"],
        ["git", "push", "-u", "origin", branch],
        ["gh", "pr", "create", "--base", "main", "--head", branch,
         "--draft", "--title", f"census: map {arch} -> {target} (auto-draft)",
         "--body", body],
    ]
    for cmd in cmds:
        r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        if r.returncode != 0:
            # branch may already exist from a prior run — try to reuse
            if "already exists" in r.stderr or "fatal: A branch named" in r.stderr:
                # checkout the existing branch, ensure it has the alias, skip commit
                subprocess.run(["git", "switch", branch], cwd=ROOT, capture_output=True)
                continue
            print(f"[autopr] cmd failed: {' '.join(cmd)}\n{r.stderr[:300]}", file=sys.stderr)
            return None
    # return the PR url from the last command — only accept a real github.com https URL
    out = r.stdout.strip()
    if not out:
        return None
    try:
        parsed = urlparse(out)
    except ValueError:
        return None
    return out if parsed.scheme == "https" and parsed.netloc == "github.com" else None


def maybe_file_draft_pr(uncovered, models=None, dry_run=None):
    """For each uncovered class, if a plausible candidate exists, open a draft PR.

    Returns list of (arch, target, pr_url_or_None).
    """
    if dry_run is None:
        dry_run = os.getenv("CENSUS_DRY_RUN") == "1"
    if os.getenv("CENSUS_SKIP_PR") == "1":
        print("[autopr] CENSUS_SKIP_PR=1 — alert only, no PR", file=sys.stderr)
        return []

    models = models or {}
    filed = []
    for arch in sorted(uncovered):
        guess = _guess(arch)
        if not guess:
            print(f"[autopr] {arch}: no plausible known-family candidate — manual", file=sys.stderr)
            continue
        target_arch, token = guess
        if _selfcheck_has(arch):
            print(f"[autopr] {arch}: already in selfcheck — manual", file=sys.stderr)
            continue
        print(f"[autopr] {arch} -> {token} (candidate from {target_arch})")
        if dry_run:
            filed.append((arch, token, "DRY-RUN"))
            continue
        if not _open_draft_pr(arch, token, models.get(arch, [])):
            filed.append((arch, token, None))
        else:
            filed.append((arch, token, "PR-OPENED"))
    return filed


if __name__ == "__main__":
    # CLI: census_autopr.py [arch] [models...]
    if len(sys.argv) < 2:
        print("usage: census_autopr.py <uncovered_arch> [model_ids...]", file=sys.stderr)
        sys.exit(2)
    maybe_file_draft_pr([sys.argv[1]], {sys.argv[1]: sys.argv[2:]})
