
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7B00C, LENGTH = 0x4FF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x2000; /* stack */
. = 0x42000;
C_C6_0_buff_0 = .;
. += 0x4000;
. = 0x46000;
B_C6_0_cons_buff_0 = .;
. += 0x2000;
. = 0x48000;
B_C6_0_cons_buff_1 = .;
. += 0x2000;
. = 0x4A000;
A_C0_6_cons_buff_0 = .;
. += 0x800;
. = 0x4A800;
A_C0_6_cons_buff_1 = .;
. += 0x800;
. = 0x4B000;
_anonymous6 = .;
. += 0xC;
. = 0x52000;
C_C5_1_buff_0 = .;
. += 0x4000;
. = 0x56000;
B_C5_1_cons_buff_0 = .;
. += 0x2000;
. = 0x58000;
B_C5_1_cons_buff_1 = .;
. += 0x2000;
. = 0x5A000;
A_C1_5_cons_buff_0 = .;
. += 0x800;
. = 0x5A800;
A_C1_5_cons_buff_1 = .;
. += 0x800;
. = 0x5B000;
_anonymous13 = .;
. += 0xC;
. = 0x62000;
C_C6_2_buff_0 = .;
. += 0x4000;
. = 0x66000;
B_C6_2_cons_buff_0 = .;
. += 0x2000;
. = 0x68000;
B_C6_2_cons_buff_1 = .;
. += 0x2000;
. = 0x6A000;
A_C2_6_cons_buff_0 = .;
. += 0x800;
. = 0x6A800;
A_C2_6_cons_buff_1 = .;
. += 0x800;
. = 0x6B000;
_anonymous22 = .;
. += 0xC;
. = 0x72000;
C_C6_1_buff_0 = .;
. += 0x4000;
. = 0x76000;
B_C6_1_cons_buff_0 = .;
. += 0x2000;
. = 0x78000;
B_C6_1_cons_buff_1 = .;
. += 0x2000;
. = 0x7A000;
A_C1_6_cons_buff_0 = .;
. += 0x800;
. = 0x7A800;
A_C1_6_cons_buff_1 = .;
. += 0x800;
. = 0x7B000;
_anonymous14 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(mm_32x64x128.o)
PROVIDE(main = core_6_3);
