
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7B00C, LENGTH = 0x4FF4
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x2000; /* stack */
. = 0x42000;
C_C0_2_buff_0 = .;
. += 0x4000;
. = 0x46000;
B_C0_2_cons_buff_0 = .;
. += 0x2000;
. = 0x48000;
B_C0_2_cons_buff_1 = .;
. += 0x2000;
. = 0x4A000;
A_C2_0_cons_buff_0 = .;
. += 0x800;
. = 0x4A800;
A_C2_0_cons_buff_1 = .;
. += 0x800;
. = 0x4B000;
_anonymous16 = .;
. += 0xC;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x72000;
C_C0_3_buff_0 = .;
. += 0x4000;
. = 0x76000;
B_C0_3_cons_buff_0 = .;
. += 0x2000;
. = 0x78000;
B_C0_3_cons_buff_1 = .;
. += 0x2000;
. = 0x7A000;
A_C3_0_cons_buff_0 = .;
. += 0x800;
. = 0x7A800;
A_C3_0_cons_buff_1 = .;
. += 0x800;
. = 0x7B000;
_anonymous24 = .;
. += 0xC;
  .bss : { *(.bss*) } > data
}
INPUT(mm_32x64x128.o)
PROVIDE(main = core_0_5);
